// <auto-generated />
using System;
using E_CommerceStore.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_CommerceStore.Migrations
{
    [DbContext(typeof(EStoreContext))]
    [Migration("20220806190737_AddBaseModelsVersion")]
    partial class AddBaseModelsVersion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("E_CommerceStore.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("Carts", (string)null);
                });

            modelBuilder.Entity("E_CommerceStore.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("CartId")
                        .HasColumnType("int");

                    b.Property<string>("ImageSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.HasIndex("BrandId")
                        .IsUnique();

                    b.HasIndex("CartId");

                    b.HasIndex("ItemTypeId")
                        .IsUnique();

                    b.HasIndex("SellerId");

                    b.ToTable("Items", (string)null);

                    b.HasCheckConstraint("Name", "LEN(Name) > 5");

                    b.HasCheckConstraint("Price", "Price > 0");
                });

            modelBuilder.Entity("E_CommerceStore.Models.ItemBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("Brands", (string)null);

                    b.HasCheckConstraint("Name", "LEN(Name) > 2", c => c.HasName("Name1"));
                });

            modelBuilder.Entity("E_CommerceStore.Models.ItemProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ItemPropertyCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PropertyValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ItemPropertyCategoryId");

                    b.ToTable("Properties", (string)null);

                    b.HasCheckConstraint("PropertyName", "LEN(PropertyName) > 4");

                    b.HasCheckConstraint("PropertyValue", "LEN(PropertyValue) > 0");
                });

            modelBuilder.Entity("E_CommerceStore.Models.ItemPropertyCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("PropertyCategories", (string)null);

                    b.HasCheckConstraint("Name", "LEN(Name) > 3", c => c.HasName("Name2"));
                });

            modelBuilder.Entity("E_CommerceStore.Models.ItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("Types", (string)null);

                    b.HasCheckConstraint("Name", "LEN(Name) > 3", c => c.HasName("Name3"));
                });

            modelBuilder.Entity("E_CommerceStore.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("E_CommerceStore.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AccountImageSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int?>("country")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasCheckConstraint("Password", "LEN(Password) > 5");
                });

            modelBuilder.Entity("OrderUser", b =>
                {
                    b.Property<int>("OrdersId")
                        .HasColumnType("int");

                    b.Property<int>("UsersInOrderId")
                        .HasColumnType("int");

                    b.HasKey("OrdersId", "UsersInOrderId");

                    b.HasIndex("UsersInOrderId");

                    b.ToTable("UserOrder", (string)null);
                });

            modelBuilder.Entity("E_CommerceStore.Models.Item", b =>
                {
                    b.HasOne("E_CommerceStore.Models.ItemBrand", "Brand")
                        .WithOne("Item")
                        .HasForeignKey("E_CommerceStore.Models.Item", "BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_CommerceStore.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId");

                    b.HasOne("E_CommerceStore.Models.ItemType", "ItemType")
                        .WithOne("Item")
                        .HasForeignKey("E_CommerceStore.Models.Item", "ItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_CommerceStore.Models.User", "ItemSeller")
                        .WithMany("Items")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Cart");

                    b.Navigation("ItemSeller");

                    b.Navigation("ItemType");
                });

            modelBuilder.Entity("E_CommerceStore.Models.ItemProperty", b =>
                {
                    b.HasOne("E_CommerceStore.Models.ItemPropertyCategory", "PropertyCategory")
                        .WithMany("CategoryProperties")
                        .HasForeignKey("ItemPropertyCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyCategory");
                });

            modelBuilder.Entity("E_CommerceStore.Models.ItemPropertyCategory", b =>
                {
                    b.HasOne("E_CommerceStore.Models.Item", "MasterItem")
                        .WithMany("Categories")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterItem");
                });

            modelBuilder.Entity("E_CommerceStore.Models.Order", b =>
                {
                    b.HasOne("E_CommerceStore.Models.Item", "Item")
                        .WithOne("Order")
                        .HasForeignKey("E_CommerceStore.Models.Order", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("E_CommerceStore.Models.User", b =>
                {
                    b.HasOne("E_CommerceStore.Models.Cart", "Cart")
                        .WithOne("Owner")
                        .HasForeignKey("E_CommerceStore.Models.User", "CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("OrderUser", b =>
                {
                    b.HasOne("E_CommerceStore.Models.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_CommerceStore.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersInOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("E_CommerceStore.Models.Cart", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Owner")
                        .IsRequired();
                });

            modelBuilder.Entity("E_CommerceStore.Models.Item", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("E_CommerceStore.Models.ItemBrand", b =>
                {
                    b.Navigation("Item")
                        .IsRequired();
                });

            modelBuilder.Entity("E_CommerceStore.Models.ItemPropertyCategory", b =>
                {
                    b.Navigation("CategoryProperties");
                });

            modelBuilder.Entity("E_CommerceStore.Models.ItemType", b =>
                {
                    b.Navigation("Item")
                        .IsRequired();
                });

            modelBuilder.Entity("E_CommerceStore.Models.User", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
